language: node_js
node_js:
- '0.10'
install:
- npm install -g grunt-cli
- npm -g install bower
- npm install
- bower install
script:
- grunt jshint test:remote
env:
  global:
  - secure: qWxE8Cml8cm35ztk4EAusV0WF7akjEjaH6GLjbAcpWTmQqLFHPbPODI0V7V6n9n2Cvxm7eV+70KTg7SgDa62pQndqlcP83mW0hnmfrbWwH0AsNYwDOnvfFDhCLDYN3dGpe7tQr0pLUNil6J/g7E6YYJmFxOrLDp3Y238c77Xdh8=
  - secure: S2opjyuFArWLEl9H/82PYcHq63XNG6u9nCYZ+CobPT+h8CpKeoNfNwdwGyVnabLftbrB4c/y+L+DHT6p1G8PIr0Cm0T97ij5SRIsiFW/MqKL9NIzLiM/euXRvrQCkKBKndPo3DqYUe1iJIVNfmT8KtcAA0krQT9x2J258bsNo2c=
